### ISSUE TITLE
Extension list is empty

### ISSUE THREAD

**Issue by brotkrueml** [rrrapha/translate_locallang#18] opened 2019-01-31 12:37 UTC
I installed the extension via composer on TYPO3 9.5.4 as a development requirement. When I navigate to the module, the "Select extension" dropdown is empty. Of course I have multiple extensions installed (local extensions via symlink in typo3conf/ext/).

**Comment by rrrapha** [comment] 2019-01-31 14:15
Hi, I am unable to reproduce this issue.
I guess it has something to do with this function:
https://github.com/rrrapha/translate_locallang/blob/57dfda6bfbd9471e46ac1a4231d08569ab96f539/Classes/Utility/TranslateUtility.php#L168
Could you check if the return value of `getConfigPath()` is correct on your system?

**Comment by rrrapha** [comment] 2019-02-01 13:34
The issue should be fixed in the latest version.
@brotkrueml Thanks for reporting!

**Closed as completed by rrrapha** 2019-02-01 13:34 UTC
